# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python 3.9 - Ubuntu Latest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f tests/test-requirements.txt ]; then pip install -r tests/test-requirements.txt; fi

      - name: Test Everything
        run: |
          python -m unittest discover -s ./tests -p "test_*.py"

      - name: Test with Coverage
        run: |
          coverage run --omit venv/*,tests/* -m unittest discover -s ./tests -p test_*.py

      - name: Coverage Report
        run: |
          coverage report